Selenium junit concurrent example
devonfw/mrchecker pull request #398
Opened 2023-06-05 07:07 UTC by RadeckiR

New example which shows how to run selenium + junit tests concurrently in the same class.

2023-06-05 07:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/devonfw/mrchecker?pullRequest=398) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/devonfw/mrchecker?pullRequest=398) before we can accept your contribution.<br/><hr/>**Rradecki** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/devonfw/mrchecker?pullRequest=398) it.</sub>

2023-06-13 09:28 UTC, klaudia-nowak requested changes

2023-06-13 09:28 UTC, klaudia-nowak commented on mrchecker-selenium-junit-concurrent-example/README.md
> +| Parallel   | Classes  |
Change parallel setting to "Tests" instead of "Classes"

2023-06-13 09:28 UTC, klaudia-nowak commented on mrchecker-selenium-junit-concurrent-example/README.md
> +
Add information about the annotation that should be added to make tests parallel within one class

2023-06-13 09:28 UTC, klaudia-nowak commented on mrchecker-selenium-junit-concurrent-example/src/test/java/com/capgemini/mrchecker/selenium/example/test/DemoConcurrentUnitTest.java
> +package com.capgemini.mrchecker.selenium.example.test;
Add one more test class with more test examples

2023-06-19 07:56 UTC, michalbabiarz commented on pom.xml
>  		<module>mrchecker-selenium-cucumber-example</module>
Correct alignment

2023-09-14 09:59 UTC, KMariusz commented
@RadeckiR Please put in the PR description the changelog (what was changed/made) and evidences.
From my perspective as an evidence it is enough to put screenshots from Allure report - general results and timeline section which will show that those test cases was executed parallel at the same time.

2023-11-29 11:36 UTC, closed without merging